site_name: Pygsuite Documentation
repo_url: https://github.com/greenmtnboy/pygsuite
repo_name: pygsuite
docs_dir: docs
pages:
  - Overview: index.md
  - Goals: goals.md
  - Features: features.md
  - Quickstart:
      - Auth: quickstart/auth.md
      - Drive: quickstart/drive/toc.md
          - Drive: quickstart/drive/drive.md
          - File: quickstart/drive/file.md
          - Folder: quickstart/drive/folder.md
      - Docs: quickstart/docs.md
      - Sheets: quickstart/sheets.md
      - Slides: quickstart/slides.md
  - Examples: ref_examples/examples.md
      - Docs: ref_examples/docs.md
      - Sheets: ref_examples/sheets.md
      - Slides: ref_examples/slides.md
  - Reference:
      - Slides: reference/markdown/slides.md
      - Sheets: reference/markdown/sheets.md
      - Docs: reference/markdown/docs.md
theme:
  name: material
  palette:
    primary: cyan
    accent: deep orange

#google_analytics:
#  - "auto"
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist
  - urlize
  - admonition
  - toc:
      permalink: true

#  - pymdownx.emoji:
#      emoji_index: !!python/name:pymdownx.emoji.twemoji
#      emoji_generator: !!python/name:pymdownx.emoji.to_svg


