site_name: Pygsuite Documentation
repo_url: https://github.com/greenmtnboy/pygsuite
repo_name: pygsuite
docs_dir: docs
# the `nav` is created by literate-nav in SUMMARY.md
theme:
  name: material
  palette:
    primary: cyan
    accent: deep orange
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist
  - admonition
  - toc:
      permalink: true
plugins:
  - search
  - section-index
  - gen-files:
      scripts:
        - docs/generate_reference_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
            show_if_no_docstring: true
          rendering:
            show_submodules: no
      watch:
        - pygsuite
